config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "pages#landing"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get "home", to: "pages#home"


  resources :concerts, only: %i[index show] do
    collection do
      patch :fetch_concerts
    end
    resources :groups, only: %i[create new]
  end

  resources :groups, only: %i[index show] do
    resources :chatrooms, only: %i[create] do
      resources :messages, only: :create
    end
  end

  get "groups/:id/chatroom", to: "chatrooms#show", as: :chatroom

  # group_id/chatroom
  resources :invitations, only: %i[index] do
    member do
      patch :accept
      patch :decline
    end
  end
  resources :profiles, only: :show

  get "search", to: "profiles#search", as: "search"
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(params[:id])
    @top_artists = @user.artists.first(10)
  end

  def search
    # Search based on what the user typed in
    ##  params[:query] gives what user typed in
    # Get the user
    user = User.search_users(params[:query]).first
    # user = User.find_by("first_name ILIKE ?", "%#{params[:query]}%")

    # Call the show action to display the user
    # We need a fail safe
    # raise
    redirect_to profile_path(user)
  end
end

app/views/profiles/show.html.erb
<%= render "shared/navbar" %>
<div id="page-container-profile">
  <div class="search">
    <%= render "shared/search-bar", placeholder: "Find your friends!", path: search_path %>
  </div>
    <div class="text-center py-2 fs-1 fw-bold username-bootstrap">
      <% if @user.photo.attached? %>
        <%= image_tag @user.photo, class: "avatar avatar-show" %>
      <% else %>
        <%= image_tag "default_avatar.jpg", class: "avatar group-avatar" %>
      <% end %>
      <%= @user.first_name + " " + @user.last_name %>
    </div>
    <h1>
    </h1>
    <div class="container px-4">
      <h2 class="text-center mb-0 fw-bold fs-5 username-attending">
        Upcoming concerts
      </h2>
      <% if @user.groups.empty? && @user == current_user %>
        <ul class="profile-artist-cards">
          <li class="card-info" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(''); background-size: cover">
            <h3 class="fs-10 fw-bold text-white text-center"> You're not going to anything yet!</h3>
          </li>
        </ul>
      <% elsif @user.groups.empty? %>
        <ul class="profile-artist-cards">
          <li class="card-info" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(''); background-size: cover">
            <h3 class="fs-10 fw-bold text-white text-center"> <%= @user.first_name %> is not going to anything yet!</h3>
          </li>
        </ul>
      <% else %>
        <ul class="profile-artist-cards">
          <% @user.groups.each do |group| %>
            <li class="card-info" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= group.concert.artist.image_url %>'); background-size: cover">
              <h3 class="fs-10 fw-bold text-white"><%= group.concert.artist.name %></h3>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div class="container px-4">
      <h2 class="text-center mb-0 fs-5 fw-bold username-attending">
        Favourite artists
      </h2>
      <ul class="profile-artist-cards">
        <% @top_artists.each do |artist| %>
          <li class="card-info" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= artist.image_url %>'); background-size: cover">
            <h3 class="fs-10 fw-bold text-white"><%= artist.name %></h3>
          </li>
        <% end %>
      </ul>
    </div>
</div>