config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "pages#landing"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get "home", to: "pages#home"


  resources :concerts, only: %i[index show] do
    collection do
      patch :fetch_concerts
    end
    resources :groups, only: %i[create new]
  end

  resources :groups, only: %i[index show] do
    resources :chatrooms, only: %i[create] do
      resources :messages, only: :create
    end
  end

  get "groups/:id/chatroom", to: "chatrooms#show", as: :chatroom

  # group_id/chatroom
  resources :invitations, only: %i[index] do
    member do
      patch :accept
      patch :decline
    end
  end
  resources :profiles, only: :show

  get "search", to: "profiles#search", as: "search"
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :group
  has_many :messages, dependent: :destroy
  validates :name, presence: true
  validates :group, presence: true
  # validates :concert_date, comparison: { greater_than: :end_date }
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @group = Group.find(params[:id])
    @chatroom = @group.chatroom
    @message = Message.new
  end

  def create; end
end

app/views/chatrooms/_chatbox.html.erb
<!-- IF YOU ARE GOING TO STYLE THIS, LET MICAH KNOW! THERE IS EXTRA STYLING IN JAVASCRIPT-->
<div class="container chatroom" data-controller="chatroom-subscription" data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>" data-chatroom-subscription-current-user-id-value="<%= current_user.id %>">

  <div class="messages" data-chatroom-subscription-target="messages">
    <% chatroom.messages.each do |msg| %>

      <div class="message-row d-flex <%= msg.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
        <div class="<%= msg.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
          <%= render "messages/message", message: msg %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="msg-input">
    <%= simple_form_for [group, chatroom, message],
      html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex" } do |f|
        %>
        <%= f.input :content,
          label: false,
          placeholder: "##{chatroom.name}",
          wrapper_html: {class: "flex-grow-1 chat-input"}
        %>
        <%= f.submit "Send", class: "send-btn mb-3" %>
      <% end %>
  </div>
</div>

app/views/chatrooms/show.html.erb
<div id="page-container-chat">
  <div class="chatroom">
    <h1 id="chatroom-name"><%= link_to "#{@chatroom.name}", group_path(@group) %></h1>
    <div class="chatroom-friends">
      <h6> Mates: </h6>
      <div id="chatroom-friend-avatars">
      <%= render "shared/index_avatars", concert: @group %>
      </div>
    </div>
    <div class="chatbox-show">
      <%= render "chatbox", chatroom: @chatroom, message: @message, group: @group %>
    </div>
  </div>
</div>
<!-- HEROKU needs to install redis. Check the lecture notes on Chat-->