config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "pages#landing"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get "home", to: "pages#home"


  resources :concerts, only: %i[index show] do
    collection do
      patch :fetch_concerts
    end
    resources :groups, only: %i[create new]
  end

  resources :groups, only: %i[index show] do
    resources :chatrooms, only: %i[create] do
      resources :messages, only: :create
    end
  end

  get "groups/:id/chatroom", to: "chatrooms#show", as: :chatroom

  # group_id/chatroom
  resources :invitations, only: %i[index] do
    member do
      patch :accept
      patch :decline
    end
  end
  resources :profiles, only: :show

  get "search", to: "profiles#search", as: "search"
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :concert
  has_many :chatrooms, dependent: :destroy
  has_many :invitations
  has_many :users, through: :invitations
  has_one :chatroom

  validates :concert, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def create
    @concert = Concert.find(params[:concert_id])
    @group = Group.new(concert: @concert)
    invitations = []
    selected_users = User.where(id: params[:user_ids])
    selected_users.each do |selected_user|
      invitations << {
        group: @group,
        user: selected_user
      }
    end
    if @group.save
      Invitation.create(invitations)
      my_own_invite = Invitation.new(group: @group, user: current_user)
      my_own_invite.status = "accepted"
      my_own_invite.save
      Chatroom.create(group: @group, name: @concert.artist.name)
      redirect_to group_path(@group)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @concert = Concert.find(params[:concert_id])
    @group = Group.new
    # users who are following the same artist. The artist is connected through the concert
    if params[:query].present?
      @users = User.search_users(params[:query])
    else
      @users = User.joins(:follows, :artists, :concerts).where('concerts.id = ?', @concert.id).uniq
    end
  end

  def show
    @group = Group.find(params[:id])
    @concert = Concert.find(@group.concert.id)
    @message = Message.new

    @accepted_invitations = @group.invitations.where(status: "accepted").includes(:user)
    @pending_invitations = @group.invitations.where(status: "pending").includes(:user)
  end

  def index
    # @groups = Group.joins(:invitations).where('invitations.user_id = ?', current_user.id)
    @groups = Group.joins(:invitations).where('invitations.user_id = ? AND invitations.status = ?', current_user.id, 1)
    # @groups = current_user.groups
    @invites = @groups.map { |group| group.invitations }.flatten
  end

  private

  def group_params
    params.require(:group).permit(:concert)
  end
end

app/views/groups/index.html.erb
<div id="page-container-groups-index">
  <div class="group-index">
    <% if @groups.count >= 1 %>
      <div class="show">
        <h1>These are the concerts you're attending!</h1>
      </div>
      <% @groups.each do |group| %>
        <%= link_to group_path(group) do %>
          <% concert = group.concert %>
          <div class="concert-card">
            <div class="img-grey" style="background-image: url(<%= concert.artist.image_url %>)"></div>
            <div class="img-gradient"></div>
            <div class="concert-info">
              <h2><strong><%= concert.artist.name %></strong></h2>
              <p><strong><%= concert.date.strftime("%A %e %B %Y") %></strong></p>
              <p><%= concert.venue %>, <%= concert.location %></p>
            </div>
            <div class="concert-avatars">
              <% group.users.without_me(current_user).first(5).each do |user|%>
                <% if user.photo.attached? %>
                  <%= image_tag user.photo, class: "avatar group-avatar" %>
                <% else %>
                  <%= image_tag "default_avatar.jpg", class: "avatar group-avatar" %>
                <% end %>
              <% end %>
              <% if group.users.without_me(current_user).count > 5 %>
                <div class="avatar">
                  <%= group.users.without_me(current_user).count - 5 %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <div class="show">
        <h1>You're not attending any concerts yet!</h1>
      </div>
      <div class="sad-duck"><%= image_tag "sad_duck.gif", class: 'sad-duck' %></div>
    <% end %>
  </div>
</div>
<%#  %>

app/views/groups/new.html.erb
<div id="page-container">

  <h1 id="group-new-h1"><%= @concert.artist.name %></h1>
  <h3 class="groups-new-h3">At <%= @concert.venue %></h3>


  <div class="friend-list">


    <div class="search">
      <%= render "shared/search-bar", placeholder: "Choose who to invite!", path: new_concert_group_path %>
    </div>

    <div class="create-group">
      <%= simple_form_for [@concert, @group] do |f| %>
          <% @users.each do |user| %>
          <% next if user == current_user  %>
          <div class="friends-invite"> <div class="avatar-name d-flex align-items-center">
            <% if user.photo.attached? %>
              <%= image_tag user.photo, class: "avatar group-avatar" %>
            <% else %>
              <%= image_tag "default_avatar.jpg", class: "avatar group-avatar" %>
            <% end %>
            <p class="ms-2 mb-0">
              <% if user.last_name.present? %>
                <%= user.first_name + " " + user.last_name %>
              <% else %>
                <%= user.first_name %>
              <% end %>
            </p>
          </div>
          <label class="switch">
            <%= check_box_tag 'user_ids[]', user.id %>
            <span class="slider round"></span>
          </label>
          </div>
          <% end %>
        <%= f.submit "Make a group!", id: "group-btn" %>
      <% end %>
    </div>
  </div>

</div>

app/views/groups/show.html.erb
<div id="page-container-groupshow">
  <div class="show">
    <div class="concert-header-center">
      <div class="img-color" style="background-image: url(<%= @concert.artist.image_url %>)"></div>
      <div class="img-gradient"></div>
      <h1 id="h1-basic-styling"> <%= @concert.artist.name %> </h1>
    </div>
    <div class="group-info-container">
      <h1>You're going!</h1>
      <div class="info-group">
        <p>📅 On <%= @concert.date.strftime("%A %e %B %Y") %></p>
        <p>From <%= @concert.date.strftime("%l:%M %P") %></p>
      </div>
      <!-- Time.current.in_time_zone("America/New_York").strftime("TZ is: %Z") # => "TZ is: EDT" -->
      <div class="info-group">
        <p>📍 At <%= @concert.venue %></p>
        <p>In <%= @concert.location %></p>
      </div>
    </div>
    <% if @pending_invitations.count > 0 %>
      <h2 class="invitation-status">🧑‍🤝‍🧑 Awaiting response from <%= pluralize(@pending_invitations.count, 'mate') %></h2>
    <% else %>
      <h2 class="invitation-status">🧑‍🤝‍🧑 No pending invitations!</h2>
    <% end %>
    <div class="invitation-box">
      <% if @pending_invitations.empty? %>
        <div>Everybody has responded.</div>
      <% else %>
        <div class="avatar-container">
          <% @pending_invitations.first(5).each do |invitation|%>
            <% if invitation.user.photo.attached? %>
              <%= image_tag invitation.user.photo, class: "avatar group-avatar" %>
            <% else %>
              <%= image_tag "default_avatar.jpg", class: "avatar group-avatar" %>
            <% end %>
          <% end %>
        </div>
        <% if @pending_invitations.count > 5 %>
          <div class="avatar-overflow">
            + <%= @pending_invitations.count - 5 %>
          </div>
        <% end %>
      <% end %>
    </div>
    <h2 class="invitation-status">🧑‍🤝‍🧑 <%= pluralize(@accepted_invitations.count, 'mate') %> going</h2>
    <div class="invitation-box">
      <% if @accepted_invitations.empty? %>
        <div>Nobody has said they're going yet!</div>
      <% else %>
        <div class="avatar-container">
          <% @accepted_invitations.each do |invitation|%>
            <% if invitation.user.photo.attached? %>
              <%= image_tag invitation.user.photo, class: "avatar group-avatar" %>
            <% else %>
              <%= image_tag "default_avatar.jpg", class: "avatar group-avatar" %>
            <% end %>
          <% end %>
        </div>
        <% if @accepted_invitations.count > 5 %>
          <div class="avatar-overflow">
            + <%= @accepted_invitations.count - 5 %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="invitation-box-2">
      <%= link_to "Chat with this group!", chatroom_path(@group), id:"show-btn-groups" %>
    </div>
  </div>