config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "pages#landing"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get "home", to: "pages#home"


  resources :concerts, only: %i[index show] do
    collection do
      patch :fetch_concerts
    end
    resources :groups, only: %i[create new]
  end

  resources :groups, only: %i[index show] do
    resources :chatrooms, only: %i[create] do
      resources :messages, only: :create
    end
  end

  get "groups/:id/chatroom", to: "chatrooms#show", as: :chatroom

  # group_id/chatroom
  resources :invitations, only: %i[index] do
    member do
      patch :accept
      patch :decline
    end
  end
  resources :profiles, only: :show

  get "search", to: "profiles#search", as: "search"
end

app/models/concert.rb
class Concert < ApplicationRecord
  belongs_to :artist
  has_many :groups, dependent: :destroy
  has_many :follows, through: :artist
  has_many :users, through: :follows

  validates :artist, presence: true
  validates :date, presence: true
  validates :venue, presence: true
  validates :location, presence: true
  validates :description, presence: true

  default_scope { order(date: :asc) }
  # default_scope where {  }
  include PgSearch::Model
  pg_search_scope :search_concerts, against: {
    venue: 'B',
    city: 'C',
  },
    associated_against: {
      :artist => { :name => 'A' }
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/concerts_controller.rb
require "erb"
include ERB::Util

class ConcertsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home]

  def index
    if params[:query].present?
      @concerts = Concert.search_concerts(params[:query])
    else
      @concerts = current_user.concerts
    end
    # @concerts = Concert.all
  end

  def show
    @concert = Concert.find(params[:id])
  end

  def fetch_concerts
    check_for_new_concerts
    redirect_to concerts_path
  end

  private

  def check_for_new_concerts
    current_user.artists.each do |artist|
      artist_concerts = concerts_from_api_for(artist)
      if artist_concerts
        artist_concerts.each do |concert|
          if concert["venue"]["country"] == "Australia"
            create_concert_unless_it_already_exists(concert, artist)
          end
        end
      end
    end
  end

  def concerts_from_api_for(artist)
    potential_concerts = HTTParty.get("https://rest.bandsintown.com/artists/#{url_encode(artist.name)}/events?app_id=#{ENV["BANDS_IN_TOWN_KEY"]}&date=upcoming")
    potential_concerts[0] && potential_concerts[0]["datetime"] ? potential_concerts : false
  end

  def create_concert_unless_it_already_exists(concert, artist)
    Concert.where(artist: artist, date: DateTime.parse(concert["datetime"])).first_or_create(
      artist: artist,
      date: DateTime.parse(concert["datetime"]),
      location: concert["venue"]["location"],
      city: concert["venue"]["city"],
      country: concert["venue"]["country"],
      description: Rails::Html::FullSanitizer.new.sanitize(concert["description"]),
      venue: concert["venue"]["name"],
      latitude: concert["venue"]["latitude"],
      longitude: concert["venue"]["longitude"]
    )
  end
end

app/views/concerts/index.html.erb
<div id="page-container-index">

  <h1 id="concert-index-h1">Upcoming concerts</h1>
  <h2 id="concert-index-h2">Invite your mates</h2>

  <div class="search">
    <%= render "shared/search-bar", placeholder: "Explore upcoming gigs", path: concerts_path %>
  </div>

  <% @concerts.each do |concert| %>
    <%= link_to concert_path(concert), class: "concert-a" do %>
      <div class="concert-card">
        <div class="img-grey" style="background-image: url(<%= concert.artist.image_url %>)"></div>
        <div class="img-gradient"></div>
        <div class="concert-info">
          <h2><strong><%= concert.artist.name %></strong></h2>
          <p><strong><%= concert.date.strftime("%A %e %B %Y") %></strong></p>
          <p><%= concert.venue %>, <%= concert.city %></p>
        </div>
        <div class="concert-avatars">

          <%= render "shared/index_avatars", concert: concert%>

        </div>
      </div>
    <% end %>
  <% end %>

  <div class="refresher">
    <div class="a-tag-center"><%= link_to "Check for new concerts!", fetch_concerts_concerts_path, data: {turbo_method: :patch} %></div>
    <p>This might take 60 - 90 seconds...</p>
    <p>Please do not refresh the page after clicking.</p>
  </div>

</div>

app/views/concerts/show.html.erb
<div id="page-container-concertshow">
  <div class="show">
    <div class="concert-header-center">
      <div class="img-color" style="background-image: url(<%= @concert.artist.image_url %>)"></div>
      <div class="img-gradient"></div>
      <h1 id="h1-basic-styling"> <%= @concert.artist.name %> </h1>
    </div>
    <h1 id="show-h1">Want to go?</h1>
    <h2 id="h2-basic-styling">Create a group to invite some friends!</h2>

    <div class="show-detail-container-last">
      <div class="show-emoji">
        📅
      </div>
      <div class="show-detail">
        <h2><%= @concert.date.strftime("%A %e %B %Y") %></h2>
        <h3>From <%= @concert.date.strftime("%l:%M %P") %></h3>
        <%# TIME DOES NOT WORK %>
        <!-- Time.current.in_time_zone("America/New_York").strftime("TZ is: %Z") # => "TZ is: EDT" -->
      </div>
    </div>
    <div class="show-detail-container-last">
      <div class="show-emoji">
        📍
      </div>
      <div class="show-detail">
        <h2>At <%= @concert.venue %></h2>
        <h3>In <%= @concert.location %></h3>
      </div>
    </div>
    <div class="show-detail-container-last">
      <div class="show-emoji">
        🧑‍🤝‍🧑
      </div>
      <div class="show-detail">
        <% unless @concert.users.without_me(current_user).count == 0 %>
          <h2><%= pluralize(@concert.users.without_me(current_user).count, 'mate') %></h2>
          <h3>might be interested</h3>
        <% else %>
          <h2>None of your friends are going to this concert...</h2>
          <h3>This will be a solo trip.</h3>
        <% end %>
      </div>
    </div>

    <div class="show-desc">
      <p><%= @concert.description %></p>
    </div>
  </div>

  <div id="show-btn-container">
    <%= link_to "Create a group!", new_concert_group_path(@concert), id:"show-btn" %>
  </div>

</div>